### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by chl916185** [awadbahaa/FAUNet#1]
Can you share the dataset?
@awadbahaa

**Comment by awadbahaa** [comment]
hi, I will share it within this week, my laptop has been stolen and I need to see if I have it backed up somewhere, ill let you know.

**Comment by awadbahaa** [comment]
Hi @chl916185 , I am sorry for the delay, here is a link for the data. It contains the original cloudless mosaic and the shapefile for the polygons. Let me know if you need anything else. Good luck. 
https://drive.google.com/file/d/1Ej5MCyYK85ztn8a_wD1ose0SFrhaYvPB/view?usp=sharing
